name: Docs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main] 
  pull_request:
    branches: [main]

  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions: write-all

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
        
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        # Path to Doxyfile
        doxyfile-path: "./dconfig" # default is ./Doxyfile
        # Working directory
        working-directory: "." # default is .
    - name: Build latex
    
      run: |
        sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra latexmk
        ls -la 
        ls -la docs
        cd docs/
        
        BUILD_DIR=$(mktemp -d)
        cp -r latex/* "$BUILD_DIR"
        cd "$BUILD_DIR"

        # Build the PDF
        latexmk -pdf -interaction=nonstopmode refman.tex || {
          echo "❌ LaTeX PDF build failed"
          exit 1
        }

        # Move the generated PDF back to the main directory
        cp refman.pdf $GITHUB_WORKSPACE/docs/documentation.pdf
        cd $GITHUB_WORKSPACE

        
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Default Doxyfile build documentation to html directory. 
        # Change the directory if changes in Doxyfile
        publish_dir: ./docs/

   
    
   
