name: Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra latexmk

      - name: Run Doxygen
        uses: mattnotmitt/doxygen-action@v1.1.0
        with:
          doxyfile-path: "./dconfig"
          working-directory: "."

      - name: Build LaTeX PDF
        working-directory: ./latex
        run: |
          make clean
          make

      - name: Prepare Documentation for Publishing
        run: |
          mkdir -p ./public
          cp -r ./docs/html/* ./public/
          cp ./latex/refman.pdf ./public/documentation.pdf

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
