name: Docs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main] 
  pull_request:
    branches: [main]

  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions: write-all

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
        
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        # Path to Doxyfile
        doxyfile-path: "./dconfig" # default is ./Doxyfile
        # Working directory
        working-directory: "." # default is .
    - name: Build LaTeX PDF
      run: |
        # Install LaTeX build tools
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra latexmk

        # Use a temp build directory
        cd docs
        BUILD_DIR=$(mktemp -d)
        cp -r latex/* "$BUILD_DIR"
        echo "BUILD_DIR=$BUILD_DIR" >> $GITHUB_ENV  # Save path for next step

        cd "$BUILD_DIR"
        head -n 100 refman.tex
         # Replace the default titlepage block with your custom one
        sed -i '/\\begin{titlepage}/,/\\end{titlepage}/c\\
        \\begin{titlepage}\\
        \\centering\\
        \\vspace*{4cm}\\
        {\\Huge \\bfseries Ecto-Trigger PDF documentation vignette\\par}\\
        \\vfill\\
        \\thispagestyle{empty}\\
        \\end{titlepage}' refman.tex
        # Remove Unwanted Sections from LaTeX
        # Remove specific \include{} lines from refman.tex
        sed -i '/\\include{namespace}/d' refman.tex
        sed -i '/\\include{hierarchy}/d' refman.tex
        sed -i '/\\include{annotated}/d' refman.tex
        sed -i '/\\include{files}/d' refman.tex
        sed -i '/\\include{namespaces}/d' refman.tex
        sed -i '/\\include{namespacemembers}/d' refman.tex
        sed -i '/\\include{classes}/d' refman.tex
        sed -i '/\\include{classmembers}/d' refman.tex
        sed -i '/\\include{pages}/d' refman.tex
        sed -i '/\\include{modules}/d' refman.tex
        sed -i '/\\include{dirs}/d' refman.tex
        head -n 100 refman.tex
        echo "✅ Removed unwanted LaTeX index sections from refman.tex"

        # Compile the PDF
        latexmk -pdf -interaction=nonstopmode refman.tex || {
          echo "❌ LaTeX PDF build failed"
          exit 1
        }

    - name: Upload PDF Artifact
      uses: actions/upload-artifact@v4
      with:
        name: documentation-pdf
        path: ${{ env.BUILD_DIR }}/refman.pdf
        
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Default Doxyfile build documentation to html directory. 
        # Change the directory if changes in Doxyfile
        publish_dir: ./docs/

   
    
   
